[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "signal", "io-util", "sync"] }

